#!/usr/bin/env bash

# upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep energy-rate | awk '{printf "%.3f\n", $2}'
awk '{getline voltage < "/sys/class/power_supply/BAT1/voltage_now"; printf "%.3f W\n", $1 * voltage / 1000000000000}' /sys/class/power_supply/BAT1/current_now
