modmap:
  - name: "Better capslock"
    remap:
      CAPSLOCK:
        held: LEFTCTRL
        alone: ESC
  - name: Global
    remap:
      # Esc key outputs backtick
      Esc: grave
      Alt_L: LEFTMETA
      LEFTMETA: Alt_L
keymap:
  - name: Alt modifier
    remap:
      Alt_R-p: KEY_UP
      Alt_R-SEMICOLON: KEY_DOWN
      Alt_R-l: KEY_LEFT
      Alt_R-APOSTROPHE: KEY_RIGHT

# Note: Right Alt navigation moved to keymap section
# virtual_modifiers:
#   - Alt_R
# keymap: - name: Turn Esc long hold into ctrl?
#     remap:
#       CapsLock:
#         remap:
#           Esc:
#             timeout_key: Ctrl_L
#             timeout_millis: 150  # timeout duration in ms
# keymap:
#   - name: Alt modifier
#     remap:
#       Alt_R-p: KEY_UP
#       Win_R-l: KEY_DOWN
      # Win_R-j: KEY_DOWN
      # Down Win_R-l: Right - name: Shift-Esc to tilde
  
  # - name: Right Alt navigation
  #   remap:
  #     Alt_R-l: left
  #     Alt_R-semicolon: down
  #     Alt_R-apostrophe: right
  #     Alt_R-p: up
#
#   - name: Kana -> Windows
#     application:
#       not: jetbrains-idea
#     remap:
#       # Use Windows since Alt is annoying in Electron apps (Slack, Nocturn)
#       KatakanaHiragana: Win_R
#
#   - name: Kana -> Alt
#     application:
#       only: jetbrains-idea
#     remap:
#       # Use Alt since Windows is annoying in IDEA
#       KatakanaHiragana: Alt_L
#
# keymap:
#   - name: IDEA (modified from Default)
#     application:
#       only: jetbrains-idea
#     remap:
#       # Emacs basic
#       # C-b: left  # for Vim
#       # C-f: right # for Vim
#       C-p: up
#       C-n: down
#
#       # Emacs word
#       Super-b: C-left
#       Super-f: C-right
#
#       # Emacs lines
#       C-a: home # TODO: Alt-C-a
#       C-e: end # TODO: Alt-C-e
#       C-k: [Shift-end, backspace] # TODO: Alt-C-k
#
#       # Alt -> Ctrl
#       M-a: C-a
#       M-z: C-z
#       M-x: C-x
#       #M-c: C-c # use C-c for Esc, M-c for copy
#       #M-v: C-v # use C-v for Vim, M-v for paste
#       #M-w: C-w # avoid conflict with prefix
#       M-t: C-t
#       M-l: C-l
#
#       # actually these are vim insert mode bindings, but compatible with shell
#       # C-w: [C-Shift-left, delete]
#
#       C-d: delete
#       Super-d: C-delete
#
#       # workaround prefix key bug
#       M-r:
#         remap:
#           '3': C-M-3
#           '0': C-M-0
#
#       # workaround
#       C-c: Esc
#
#   - name: Google Search
#     application:
#       only: Google-chrome
#     remap:
#       Super-o: C-Shift-tab
#       Super-p: C-tab
#       Super-s: C-f
#
#   - name: Terminal
#     application:
#       only: Gnome-terminal
#     remap:
#       Super-o: M-o
#       Super-p: M-p
#       Super-j: M-j
#       Super-k: M-k
#       Super-r: M-r
#       Super-b: M-b
#       Super-f: M-f
#       Super-d: M-d
#       Super-i: M-i
#       Super-w: M-w
#       Super-w: M-w
#       Super-t: M-t
#       Super-c: M-c
#       Super-v: M-v
#
#   - name: Nocturn
#     application:
#       only: Nocturn
#     remap:
#       Super-j: M-j
#       Super-k: M-k
#       Super-o: M-o
#       Super-p: M-p
#       Super-Enter: Shift-Enter
#
#   - name: Slack
#     application:
#       only: Slack
#     remap:
#       Super-o: C-Shift-tab
#       Super-p: C-tab
#       Super-n: C-k
#       Super-k: M-up
#       Super-j: M-down
#       C-M-k: Shift-Alt-up
#       C-M-j: Shift-Alt-down
#
#       Super-1: C-1
#       Super-2: C-2
#       Super-3: C-3
#       Super-4: C-4
#       Super-5: C-5
#       Super-6: C-6
#       Super-7: C-7
#       Super-8: C-8
#       Super-9: C-9
#
#   - name: Default -- some of these are overridden by the above definitions
#     application:
#       not: [Google-chrome, Slack, Gnome-terminal, jetbrains-idea]
#     remap:
#       # Emacs basic
#       C-b: left
#       C-f: right
#       C-p: up
#       C-n: down
#
#       # Emacs word
#       Super-b: C-left
#       Super-f: C-right
#
#       # Emacs lines
#       C-a: home # TODO: Alt-C-a
#       C-e: end # TODO: Alt-C-e
#       C-k: [Shift-end, backspace] # TODO: Alt-C-k
#
#       # Alt -> Ctrl
#       Super-a: C-a
#       Super-z: C-z
#       Super-x: C-x
#       Super-c: C-c
#       Super-v: C-v
#       Super-w: C-w
#       Super-t: C-t
#       Super-l: C-l
#
#       # Tab changes + Alt-Enter simulation
#       Super-o: C-Shift-tab
#       Super-p: C-tab
#       Super-Enter: M-Enter
#
#       # actually these are vim insert mode bindings, but compatible with shell
#       C-w: [C-Shift-left, delete]
#
#       C-d: delete
#       Super-d: C-delete
#
#       # Underscore without Shift
#       RO: Shift-RO
#
#       # SKK hack for Chrome
#       C-j: C-m
